server:
  port: 9001

# 开启降级feign.hystrix
#feign:
#  hystrix:
#    enabled: true

# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka注册自己
    fetch-registry: true  #要不要去注册中心获取其他服务的地址
    service-url:
      defaultZone: http://eureka7001:7001/eureka/

# 配置上传文件大小
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 100MB

feign:
  client:
    config:
      default:
        #超时时间默认为1s
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 10000
